In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

reason1  reason2  reason3  reason4  Month Value  Day of Week  \
0        0        0        0        1            7            1   
1        0        0        0        0            7            1   
2        0        0        0        1            7            2   
3        1        0        0        0            7            3   
4        0        0        0        1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

reason1  reason2  reason3  reason4  Month Value  Day of Week  \
0        0        0        0        1            7            1   
1        0        0        0        0            7            1   
2        0        0        0        1            7            2   
3        1        0        0        0            7            3   
4        0        0        0        1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [7]:
data_preprocessed['Excessive Absenteeism'].value_counts()

0    381
1    319
Name: Excessive Absenteeism, dtype: int64

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
#data_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)
#data_targets.head()

#Backward Elimination (eliminate columns with insignificant weights)
data_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Distance to Work','Daily Work Load Average',
                                      'Day of Week'],axis=1)
data_targets.head()

reason1  reason2  reason3  reason4  Month Value  Transportation Expense  \
0        0        0        0        1            7                     289   
1        0        0        0        0            7                     118   
2        0        0        0        1            7                     179   
3        1        0        0        0            7                     279   
4        0        0        0        1            7                     289   

   Age  Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0   33               30          0         2     1                      1  
1   50               31          0         1     0                      0  
2   38               31          0         0     0                      0  
3   39               24          0         2     0                      1  
4   33               30          0         2     1                      0

In [10]:
unscaled_data = data_targets.iloc[:,:-1]

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
absenteeism_scaler = StandardScaler()

In [13]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [14]:
# check what are all columns that we've got
unscaled_data.columns.values

array(['reason1', 'reason2', 'reason3', 'reason4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [15]:
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['reason1', 'reason2', 'reason3', 'reason4','Education']

In [16]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_data.columns.values if x not in columns_to_omit]
columns_to_scale

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets']

In [17]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

In [18]:
absenteeism_scaler.fit(unscaled_data)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [19]:
# standardizes the data, using the transform method 
# in the last line, we fitted the data - in other words
# we found the internal parameters of a model that will be used to transform data. 
# transforming applies these parameters to our data
# note that when you get new data, you can just call 'scaler' again and transform it in the same way as now
scaled_data = absenteeism_scaler.transform(unscaled_data)

In [20]:
scaled_data

reason1  reason2  reason3  reason4  Month Value  Transportation Expense  \
0          0        0        0        1     0.182726                1.005844   
1          0        0        0        0     0.182726               -1.574681   
2          0        0        0        1     0.182726               -0.654143   
3          1        0        0        0     0.182726                0.854936   
4          0        0        0        1     0.182726                1.005844   
5          0        0        0        1     0.182726               -0.654143   
6          0        0        0        1     0.182726                2.092381   
7          0        0        0        1     0.182726                0.568211   
8          0        0        1        0     0.182726               -1.016322   
9          0        0        0        1     0.182726                0.190942   
10         1        0        0        0     0.182726                0.568211   
11         1        0        0        0     0.182726                0.568211   
12         1        0        0        0     0.182726                0.568211   
13         1        0        0        0     0.182726               -0.654143   
14         0        0        0        1     0.182726               -0.654143   
15         1        0        0        0     0.182726                0.356940   
16         0        0        0        1     0.182726               -0.654143   
17         0        0        1        0     0.182726               -0.654143   
18         1        0        0        0     0.182726               -0.503235   
19         0        0        0        1     0.468236                0.387122   
20         1        0        0        0     0.468236                1.624567   
21         1        0        0        0     0.468236               -0.654143   
22         1        0        0        0     0.468236                2.092381   
23         0        0        0        1     0.468236                0.568211   
24         0        0        1        0     0.468236                1.005844   
25         0        0        0        1     0.468236                2.092381   
26         0        0        0        1     0.468236                1.005844   
27         0        0        0        1     0.468236               -0.986140   
28         0        0        1        0     0.468236                1.005844   
29         0        0        0        1     0.468236               -0.654143   
..       ...      ...      ...      ...          ...                     ...   
670        0        0        0        1    -0.673803               -1.016322   
671        0        0        1        0    -0.673803                0.040034   
672        1        0        0        0    -0.673803               -1.574681   
673        0        0        0        1    -0.673803               -0.654143   
674        0        0        0        1    -0.388293                0.190942   
675        0        0        1        0    -0.388293                0.040034   
676        0        0        0        1    -0.388293                0.190942   
677        1        0        0        0    -0.388293               -1.574681   
678        0        0        0        1    -0.388293                0.190942   
679        1        0        0        0    -0.388293               -0.654143   
680        0        0        0        1    -0.388293                1.036026   
681        1        0        0        0    -0.388293                0.040034   
682        0        0        1        0    -0.388293                1.171843   
683        0        0        0        1    -0.388293                0.040034   
684        0        0        0        1    -0.388293               -0.654143   
685        0        0        0        1    -0.388293               -1.574681   
686        1        0        0        0    -0.388293               -1.574681   
687        0        0        0        1    -0.388293               -1.574681   
688  

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
train_test_split(scaled_data, targets)

[     reason1  reason2  reason3  reason4  Month Value  Transportation Expense  \
 504        0        0        0        1     0.753746               -0.654143   
 566        0        0        0        1     1.610276                0.040034   
 304        0        0        0        1     1.039256                0.190942   
 678        0        0        0        1    -0.388293                0.190942   
 144        1        0        0        0    -1.244823                2.499833   
 19         0        0        0        1     0.468236                0.387122   
 495        0        0        0        1     0.753746                0.356940   
 468        0        1        0        0     0.182726                1.171843   
 675        0        0        1        0    -0.388293                0.040034   
 249        0        0        1        0     0.182726                1.005844   
 342        0        0        0        1     1.610276                0.190942   
 664        1        0      

In [23]:
x_train, x_test, y_train, y_test = train_test_split(scaled_data, targets, train_size=0.8,
                                                    shuffle = 'true',  #shuffle tru by default
                                                    random_state = 7)  #shuffle but not randomized everytime we run the code

In [24]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [26]:
reg = LogisticRegression()

In [27]:
reg.fit(x_train, y_train)

E:\Anaconda\Python\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
reg.score(x_train, y_train)

0.7785714285714286

In [29]:
#80% accuracy

In [30]:
#manually check accuracy i.e. build score function

In [31]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,

In [32]:
y_train

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,

In [33]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False, False,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False, False,
        True, False,  True,  True, False, False,  True,  True, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [34]:
np.sum((model_outputs == y_train))
#as true = 1 & false = 0

436

In [35]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.7785714285714286

In [36]:
#To calculate Weights(coeffecients) and Biases(intercepts)

In [37]:
reg.intercept_

array([-1.5399373])

In [38]:
reg.coef_

array([[ 2.82174901,  0.50912413,  2.95869659,  0.73767369,  0.06334092,
         0.60851046, -0.18245548,  0.32113222,  0.08703281,  0.40225936,
        -0.30816547]])

In [39]:
 unscaled_data.columns.values

array(['reason1', 'reason2', 'reason3', 'reason4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [40]:
feature_name = unscaled_data.columns.values

In [41]:
summary_table = pd.DataFrame(columns=['Feature Names'], data = feature_name)

summary_table['Coeffecients'] = np.transpose(reg.coef_)

In [42]:
summary_table

Feature Names  Coeffecients
0                  reason1      2.821749
1                  reason2      0.509124
2                  reason3      2.958697
3                  reason4      0.737674
4              Month Value      0.063341
5   Transportation Expense      0.608510
6                      Age     -0.182455
7          Body Mass Index      0.321132
8                Education      0.087033
9                 Children      0.402259
10                    Pets     -0.308165

In [43]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Names  Coeffecients
0                Intercept     -1.539937
1                  reason1      2.821749
2                  reason2      0.509124
3                  reason3      2.958697
4                  reason4      0.737674
5              Month Value      0.063341
6   Transportation Expense      0.608510
7                      Age     -0.182455
8          Body Mass Index      0.321132
9                Education      0.087033
10                Children      0.402259
11                    Pets     -0.308165

In [44]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coeffecients)
summary_table

Feature Names  Coeffecients  Odds Ratio
0                Intercept     -1.539937    0.214395
1                  reason1      2.821749   16.806219
2                  reason2      0.509124    1.663833
3                  reason3      2.958697   19.272835
4                  reason4      0.737674    2.091065
5              Month Value      0.063341    1.065390
6   Transportation Expense      0.608510    1.837692
7                      Age     -0.182455    0.833222
8          Body Mass Index      0.321132    1.378688
9                Education      0.087033    1.090932
10                Children      0.402259    1.495199
11                    Pets     -0.308165    0.734794

In [45]:
summary_table.sort_values('Odds Ratio', ascending = False)

Feature Names  Coeffecients  Odds Ratio
3                  reason3      2.958697   19.272835
1                  reason1      2.821749   16.806219
4                  reason4      0.737674    2.091065
6   Transportation Expense      0.608510    1.837692
2                  reason2      0.509124    1.663833
10                Children      0.402259    1.495199
8          Body Mass Index      0.321132    1.378688
9                Education      0.087033    1.090932
5              Month Value      0.063341    1.065390
7                      Age     -0.182455    0.833222
11                    Pets     -0.308165    0.734794
0                Intercept     -1.539937    0.214395

In [ ]:
#Testing

In [46]:
reg.score(x_test,y_test)

0.7428571428571429

In [ ]:
#in 74.2% of cases, model will predict correctly if a person is going to be excessively absent

In [47]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.76682306, 0.23317694],
       [0.87725305, 0.12274695],
       [0.45719054, 0.54280946],
       [0.30602789, 0.69397211],
       [0.21657019, 0.78342981],
       [0.7434289 , 0.2565711 ],
       [0.75123055, 0.24876945],
       [0.63990045, 0.36009955],
       [0.63175696, 0.36824304],
       [0.17508283, 0.82491717],
       [0.7434289 , 0.2565711 ],
       [0.87725305, 0.12274695],
       [0.76682306, 0.23317694],
       [0.26346408, 0.73653592],
       [0.73607722, 0.26392278],
       [0.85801515, 0.14198485],
       [0.35049938, 0.64950062],
       [0.36509373, 0.63490627],
       [0.76357387, 0.23642613],
       [0.13911568, 0.86088432],
       [0.77682091, 0.22317909],
       [0.45719054, 0.54280946],
       [0.62801903, 0.37198097],
       [0.7434289 , 0.2565711 ],
       [0.05626444, 0.94373556],
       [0.62730645, 0.37269355],
       [0.76029356, 0.23970644],
       [0.83777046, 0.16222954],
       [0.27209107, 0.72790893],
       [0.62330326, 0.37669674],
       [0.

In [48]:
#all probabilities of being 1
predicted_proba[:,1]

array([0.23317694, 0.12274695, 0.54280946, 0.69397211, 0.78342981,
       0.2565711 , 0.24876945, 0.36009955, 0.36824304, 0.82491717,
       0.2565711 , 0.12274695, 0.23317694, 0.73653592, 0.26392278,
       0.14198485, 0.64950062, 0.63490627, 0.23642613, 0.86088432,
       0.22317909, 0.54280946, 0.37198097, 0.2565711 , 0.94373556,
       0.37269355, 0.23970644, 0.16222954, 0.72790893, 0.37669674,
       0.37693121, 0.7722671 , 0.27100897, 0.87843431, 0.93450807,
       0.61141913, 0.36847535, 0.59582282, 0.5740145 , 0.82952969,
       0.83547766, 0.76733513, 0.24636004, 0.23642613, 0.62016618,
       0.43501443, 0.16973894, 0.2565711 , 0.53585303, 0.12274695,
       0.44318013, 0.61160997, 0.78334771, 0.23317694, 0.16299081,
       0.18016385, 0.13704191, 0.65360633, 0.23317694, 0.23642613,
       0.2354977 , 0.27100897, 0.14198485, 0.35524433, 0.72431244,
       0.08199274, 0.42000243, 0.23317694, 0.15737363, 0.27100897,
       0.59146032, 0.90658611, 0.08906118, 0.81848164, 0.28185

In [50]:
import pickle

In [51]:
with open('Absentee_model','wb') as file:
    pickle.dump(reg,file)

In [52]:
with open('Absentee_scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)